const MUSIC_CATEGORIES = [
  "HINDI FILM MUSIC",
  "DEVOTIONAL MUSIC",
  "SPIRITUAL MUSIC",
  "INDIAN FOLK MUSIC",
  "SUFI POETRY",
  "GHAZAL",
  "HINDUSTANI CLASSICAL VOCAL",
  "HINDUSTANI CLASSICAL INSTRUMENTAL",
  "CARNATIC CLASSICAL VOCAL",
  "CARNATIC CLASSICAL INSTRUMENTAL",
  "HINDI POP",
  "ENGLISH POP",
  "GLOBAL-WORLD MUSIC",
  "ROCK N ROLL",
  "JAZZ"
];

module.exports = { MUSIC_CATEGORIES };
